# Generated by Django 4.1.1 on 2022-09-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmsapi', '0003_document_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='products/')),
                ('price', models.FloatField()),
            ],
        ),
    ]
